INSERT INTO TODO (ID,DESCRIPTION,DONE,TARGET_DATE,USERNAME)
VALUES (100001,'DS PROJECT',FALSE,CURRENT_DATE(),'harshit');

INSERT INTO TODO (ID,DESCRIPTION,DONE,TARGET_DATE,USERNAME)
VALUES (100002,'POIS ASSIGNMENT',FALSE,CURRENT_DATE(),'harshit');

INSERT INTO TODO (ID,DESCRIPTION,DONE,TARGET_DATE,USERNAME)
VALUES (100003,'DISASTER PROJECT',FALSE,CURRENT_DATE(),'harshit');